
export const database =

    [
        {
            "id": "1",
            "quiebre": "BO LINEA DE RESCATE MXA",
            "motivo": "NO APLICA",
            "subMotivo": "OPCION INCORRECTA",
            "subNivel": "NO APLICA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {


            "quiebre": "BO LINEA DE RESCATE MXA",
            "motivo": "NO APLICA",
            "subMotivo": "PEDIDO CMS",
            "subNivel": "NO APLICA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {


            "quiebre": "BO LINEA DE RESCATE MXA",
            "motivo": "NO APLICA",
            "subMotivo": "ORDEN NO INICIADA",
            "subNivel": "NO APLICA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {

            "quiebre": "BO LINEA DE RESCATE MXA",
            "motivo": "NO APLICA",
            "subMotivo": "ORDEN NO REALIZADA",
            "subNivel": "NO APLICA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {

            "quiebre": "BO LINEA DE RESCATE MXA",
            "motivo": "CLIENTE NO CONTESTA",
            "subMotivo": "CLIENTE NO CONTESTA",
            "subNivel": "SE RECHAZA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {

            "quiebre": "BO LINEA DE RESCATE MXA",
            "motivo": "CLIENTE NO CONTESTA",
            "subMotivo": "GEOLOCALIZACION INCORRECTA",
            "subNivel": "SE RECHAZA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "BO LINEA DE RESCATE MXA",
            "motivo": "CLIENTE NO CONTESTA",
            "subMotivo": "GEOLOCALIZACION CORRECTA",
            "subNivel": "SE CANCELA Y GENERA AVE",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true

        },
        {

            "quiebre": "BO LINEA DE RESCATE MXA",
            "motivo": "CLIENTE NO CONTESTA",
            "subMotivo": "GEOLOCALIZACION CORRECTA",
            "subNivel": "SE AGENDA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {

            "quiebre": "BO LINEA DE RESCATE MXA",
            "motivo": "CLIENTE NO CONTESTA",
            "subMotivo": "NUM NO EXISTE",
            "subNivel": "SE CANCELA Y GENERA AVE",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "BO LINEA DE RESCATE MXA",
            "motivo": "CLIENTE NO CONTESTA",
            "subMotivo": "TELF FUERA DE SERVICIO",
            "subNivel": "SE CANCELA Y GENERA AVE",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "quiebre": "BO LINEA DE RESCATE MXA",
            "motivo": "CLIENTE POSTERGA",
            "subMotivo": "CON CUPO",
            "subNivel": "SE AGENDA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "quiebre": "BO LINEA DE RESCATE MXA",
            "motivo": "CLIENTE POSTERGA",
            "subMotivo": "SIN CUPO",
            "subNivel": "SE AGENDA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "quiebre": "BO LINEA DE RESCATE MXA",
            "motivo": "CLIENTE POSTERGA",
            "subMotivo": "CAIDA AGENDADOR",
            "subNivel": "SE AGENDA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "quiebre": "BO LINEA DE RESCATE MXA",
            "motivo": "CLIENTE DESEA OTRO PAQUETE",
            "subMotivo": "DESEA OTRO PAQUETE",
            "subNivel": "SE CANCELA Y GENERA AVE",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true,

        },
        {
            "quiebre": "bo linea de rescate mxa",
            "quiebre": "BO LINEA DE RESCATE MXA",
            "motivo": "DUPLICIDAD DE PEDIDO",
            "subMotivo": "DUPLICIDAD DE PEDIDO",
            "subNivel": "SE CANCELA Y GENERA AVE",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "quiebre": "BO LINEA DE RESCATE MXA",
            "motivo": "OPOSICION DE VECINOS",
            "subMotivo": "OPOSICION DE VECINO",
            "subNivel": "SE CANCELA Y GENERA AVE",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "quiebre": "BO LINEA DE RESCATE MXA",
            "motivo": "MAL EMITIDA",
            "subMotivo": "MAL EMITIDA",
            "subNivel": "SE CANCELA Y GENERA AVE",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "quiebre": "BO LINEA DE RESCATE MXA",
            "motivo": "SI ES MXA MOT TECNICO",
            "subMotivo": "DEVUELTO POR TOA",
            "subNivel": "SE CANCELA Y GENERA AVE",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "quiebre": "BO LINEA DE RESCATE MXA",
            "motivo": "SI ES MXA MOT TECNICO",
            "subMotivo": "DEVUELTO POR TOOLBOX",
            "subNivel": "SE CANCELA Y GENERA AVE",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "quiebre": "BO LINEA DE RESCATE MXA",
            "motivo": "NO ES MXA MOT TECNICO",
            "subMotivo": "DEVUELTO POR TOA",
            "subNivel": "SE ACEPTA DEVUELTA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "quiebre": "BO LINEA DE RESCATE MXA",
            "motivo": "NO ES MXA MOT TECNICO",
            "subMotivo": "DEVUELTO POR TOOLBOX",
            "subNivel": "SIN GESTION",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "quiebre": "BO LINEA DE RESCATE MXA",
            "motivo": "INCIDENCIA",
            "subMotivo": "CAIDA DE SISTEMA",
            "subNivel": "VISOR",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "quiebre": "BO LINEA DE RESCATE MXA",
            "motivo": "NO APLICA",
            "subMotivo": "SIN MARCA",
            "subNivel": "NO APLICA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "quiebre": "BO MIGRA X AVERIA",
            "motivo": "VALIDACION",
            "subMotivo": "CON CUPO",
            "subNivel": "SE AGENDA",
            "estado": "PENDIENTE",
            "tiempoRetorno": 24,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "quiebre": "BO MIGRA X AVERIA",
            "motivo": "VALIDACION",
            "subMotivo": "SIN CUPO",
            "subNivel": "SE AGENDA",
            "estado": "PENDIENTE",
            "tiempoRetorno": 24,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "quiebre": "BO MIGRA X AVERIA",
            "motivo": "VALIDACION",
            "subMotivo": "SIN FFTT",
            "subNivel": "SE GENERA AVERIA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "quiebre": "BO MIGRA X AVERIA",
            "motivo": "VALIDACION",
            "subMotivo": "LINE ID INCORRECTO",
            "subNivel": "SE GENERA AVERIA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "VALIDACION",
            "subMotivo": "ERROR COMPONENTE",
            "subNivel": "SE GENERA AVERIA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SEGUIMIENTO",
            "subMotivo": "MIG INSTALADA",
            "subNivel": "COMPLETADO EN TOA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SEGUIMIENTO",
            "subMotivo": "MIG INICIADA",
            "subNivel": "INICIADO EN TOA",
            "estado": "PENDIENTE",
            "tiempoRetorno": 6,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SEGUIMIENTO",
            "subMotivo": "SE CANCELA MIG",
            "subNivel": "SE GENERA AVERIA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SEGUIMIENTO",
            "subMotivo": "SE CANCELA MIG",
            "subNivel": "YA TENIA AVERIA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SEGUIMIENTO",
            "subMotivo": "MIG PENDIENTE",
            "subNivel": "PENDIENTE TOA",
            "estado": "PENDIENTE",
            "tiempoRetorno": 6,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "NO APLICA",
            "subMotivo": "SIN MARCA MxA",
            "subNivel": "NO APLICA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "VALIDACION",
            "subMotivo": "ESTADO ABIERTO +SIMPLE",
            "subNivel": "SE GENERA AVERIA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "VALIDACION",
            "subMotivo": "SIN FFTT",
            "subNivel": "SIN FFTT",
            "estado": "PENDIENTE",
            "tiempoRetorno": 1,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "VALIDACION",
            "subMotivo": "ESTADO ABIERTO +SIMPLE",
            "subNivel": "ESTADO ABIERTO +SIMPLE",
            "estado": "PENDIENTE",
            "tiempoRetorno": 1,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "INCIDENCIA",
            "subMotivo": "CAIDA DE SISTEMA",
            "subNivel": "VISOR",
            "estado": "PENDIENTE",
            "tiempoRetorno": 6,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "VALIDACION",
            "subMotivo": "CANCELADO LEGADO",
            "subNivel": "TIENE MIGRA MXA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "VALIDACION",
            "subMotivo": "CANCELADO LEGADO",
            "subNivel": "SE GENERA AVERIA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "VALIDACION",
            "subMotivo": "CANCELADO LEGADO",
            "subNivel": "YA TENIA AVERIA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "VALIDACION",
            "subMotivo": "NO FIGURA EN MAS SIMPLE",
            "subNivel": "NO FIGURA EN MAS SIMPLE",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SEGUIMIENTO",
            "subMotivo": "MIG CANCELADA",
            "subNivel": "SE GENERA AVERIA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SEGUIMIENTO",
            "subMotivo": "MIG CANCELADA",
            "subNivel": "YA TENIA AVERIA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SEGUIMIENTO",
            "subMotivo": "SE CANCELA MIG",
            "subNivel": "NO REQUIERE AVERIA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SEGUIMIENTO",
            "subMotivo": "MIG CANCELADA",
            "subNivel": "NO REQUIERE AVERIA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },


        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "CLIENTE NO IDENTIFICADO",
            "subMotivo": "BUENOS PARAMETROS",
            "subNivel": "SE CANCELA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "CLIENTE NO DESEA",
            "subMotivo": "BUENOS PARAMETROS",
            "subNivel": "SE CANCELA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "CLIENTE POSTERGA",
            "subMotivo": "AGENDA MAYOR 15 DIAS",
            "subNivel": "SE CANCELA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "CLTE EN CASA DESEA VISITA",
            "subMotivo": "DIRECCION INCOMPLETA",
            "subNivel": "SE RECHAZA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "ERROR DE DIRECCION",
            "subMotivo": "OTRO DISTRITO",
            "subNivel": "SE CANCELA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "CLTE EN CASA DESEA VISITA",
            "subMotivo": "DIRECCION INCOMPLETA",
            "subNivel": "SE RECHAZA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SI ES MXA MOT TECNICO",
            "subMotivo": "BK ESPECIALIZADO",
            "subNivel": "SE RECHAZA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SI ES MXA MOT TECNICO",
            "subMotivo": "BK ESPECIALIZADO",
            "subNivel": "SE AGENDA SLA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "CLIENTE AUSENTE",
            "subMotivo": "MALOS PARAMETROS",
            "subNivel": "SE SUSPENDE",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "CLIENTE AUSENTE",
            "subMotivo": "BUENOS PARAMETROS",
            "subNivel": "SE SUSPENDE",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "CLIENTE AUSENTE",
            "subMotivo": "CLIENTE AUSENTE",
            "subNivel": "SE CANCELA Y GENERA AVE",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "CLTE EN CASA DESEA VISITA",
            "subMotivo": "CLTE ACEPTA MIGRA CON ARGUMENTARIO",
            "subNivel": "SE RECHAZA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "CLTE EN CASA DESEA VISITA",
            "subMotivo": "CLTE REQUIERE ATENCION TECNICA",
            "subNivel": "SE RECHAZA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "RECHAZADO",
            "subMotivo": "FFTT DIFERENTE ORIGEN",
            "subNivel": "NO APLICA SOLICITUD",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true,

        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "RECHAZADO",
            "subMotivo": "FOTO NO LEGIBLE",
            "subNivel": "NO APLICA SOLICITUD",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true,

        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "RECHAZADO",
            "subMotivo": "OTRO NODO",
            "subNivel": "NO APLICA SOLICITUD",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "RECHAZADO",
            "subMotivo": "MISMO DIVISOR",
            "subNivel": "NO APLICA SOLICITUD",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "REASIGNADO",
            "subMotivo": "OTRO DIVISOR",
            "subNivel": "PROCEDER CON INSTALACIÓN",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "NO APLICA",
            "subMotivo": "NO CORRESPONDE",
            "subNivel": "NO CORRESPONDE",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "NO APLICA",
            "subMotivo": "YA REASIGNADO",
            "subNivel": "YA REASIGNADO",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "NO APLICA",
            "subMotivo": "YA REASIGNADO",
            "subNivel": "DIFERENTE BORNE SOLICITADO",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "NO APLICA",
            "subMotivo": "NO INICIADO EN TOA",
            "subNivel": "COMPLETADO EN TOA NO REASIGNADO",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "NO APLICA",
            "subMotivo": "NO INICIADO EN TOA",
            "subNivel": "COMPLETADO EN TOA y REASIGNADO",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "NO APLICA",
            "subMotivo": "NO INICIADO EN TOA",
            "subNivel": "SUSPENDIDO/CANCELADO/RECHAZADO",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "RECHAZADO",
            "subMotivo": "TECNICO NO SE ENCUENTRA EN LA DIRECCIÓN",
            "subNivel": "NO APLICA SOLICITUD",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "RECHAZADO",
            "subMotivo": "ERROR DE DIRECCIÓN",
            "subNivel": "NO APLICA SOLICITUD",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "REASIGNADO",
            "subMotivo": "OTRO DIVISOR",
            "subNivel": "POR COORDINAR INSPECCIÓN",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {

            "quiebre": "BO SOPORTE ACTIVACION OTRO DIVISOR",
            "motivo": "CON ACTUACION",
            "subMotivo": "CONFIGURACION DE MODEM",
            "subNivel": "RECONFIGURACION DE ONU",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "CON ACTUACION",
            "subMotivo": "CONFIGURACION DE MODEM",
            "subNivel": "SE REINICIA MODEM",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "CON ACTUACION",
            "subMotivo": "CAMBIO DE DIVISOR",
            "subNivel": "CON CAMBIO DE OLT",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "CON ACTUACION",
            "subMotivo": "CAMBIO DE DIVISOR",
            "subNivel": "SIN CAMBIO DE OLT",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "CON ACTUACION",
            "subMotivo": "MODEM NO ESTABLECE SESION",
            "subNivel": "CAMBIO DE MODEM/DESPROVISIONAR",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SIN ACTUACION",
            "subMotivo": "BOLETA MAL GENERADA",
            "subNivel": "SIN LAN ID",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SIN ACTUACION",
            "subMotivo": "ERROR DE TOKEN",
            "subNivel": "TOKEN ERRADO",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SIN ACTUACION",
            "subMotivo": "ERROR DE TOKEN",
            "subNivel": "NO INSTALA CON TOKEN",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SIN ACTUACION",
            "subMotivo": "FFTT ERRONEA",
            "subNivel": "CTO NO CORRESPONDE",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SIN ACTUACION",
            "subMotivo": "MODEM NO SINCRONIZA",
            "subNivel": "PROBLEMAS  DE CONECTIVIDAD",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SIN ACTUACION",
            "subMotivo": "MODEM NO SINCRONIZA",
            "subNivel": "MALOS PARÃMETROS MODEM",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "EN PROCESO",
            "subMotivo": "PENDIENTE RESPUESTA PANGEA",
            "subNivel": "ESPERE CONFIRMACIÓN",
            "estado": "PENDIENTE",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "RECHAZADO",
            "subMotivo": "FOTO MANIPULADA",
            "subNivel": "NO APLICA SOLICITUD",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "RECHAZADO",
            "subMotivo": "CTO MANIPULADO",
            "subNivel": "NO APLICA SOLICITUD",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "EN PROCESO",
            "subMotivo": "DERIVADO A ESPECIALISTA TDP",
            "subNivel": "ESPERE CONFIRMACIÓN",
            "estado": "PENDIENTE",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "EN PROCESO",
            "subMotivo": "DERIVADO A ESPECIALISTA PANGEA",
            "subNivel": "ESPERE CONFIRMACIÓN",
            "estado": "PENDIENTE",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SEGUIMIENTO",
            "subMotivo": "MIG CANCELADA",
            "subNivel": "SE REINGRESA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SEGUIMIENTO",
            "subMotivo": "MIG CANCELADA",
            "subNivel": "SE REINGRESA Y SE GENERA AVE",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SEGUIMIENTO",
            "subMotivo": "MIG CANCELADA",
            "subNivel": "SE REINGRESA YA TIENE AVE",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SEGUIMIENTO",
            "subMotivo": "DEMORA EN CANCELACION",
            "subNivel": "NO PERMITE REINGRESAR",
            "estado": "PENDIENTE",
            "tiempoRetorno": 6,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SEGUIMIENTO",
            "subMotivo": "ORDEN EN VUELO",
            "subNivel": "NO PERMITE REINGRESAR",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SEGUIMIENTO",
            "subMotivo": "SERVICIO EN COBRANZA",
            "subNivel": "NO PERMITE REINGRESAR",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SEGUIMIENTO",
            "subMotivo": "SIN COBERTURA FTTH",
            "subNivel": "NO PERMITE REINGRESAR",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },


        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "INCIDENCIA",
            "subMotivo": "CAIDA DE SISTEMA",
            "subNivel": "DITO",
            "estado": "PENDIENTE",
            "tiempoRetorno": 1,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SEGUIMIENTO",
            "subMotivo": "SERVICIO SUSPENDIDO",
            "subNivel": "NO PERMITE REGISTRAR AVERIA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "INCIDENCIA",
            "subMotivo": "CAIDA DE SISTEMA",
            "subNivel": "DWP",
            "estado": "PENDIENTE",
            "tiempoRetorno": 1,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SEGUIMIENTO",
            "subMotivo": "MIG CANCELADA",
            "subNivel": "SE REINGRESA NO REQ AVE",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SEGUIMIENTO",
            "subMotivo": "MIG PENDIENTE",
            "subNivel": "SE REAGENDA CON CUPO ",
            "estado": "PENDIENTE",
            "tiempoRetorno": 24,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "SEGUIMIENTO",
            "subMotivo": "MIG PENDIENTE",
            "subNivel": "SE REAGENDA SIN CUPO ",
            "estado": "PENDIENTE",
            "tiempoRetorno": 24,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "INCIDENCIA",
            "subMotivo": "CAIDA DE SISTEMA",
            "subNivel": "AGENDADOR ",
            "estado": "PENDIENTE",
            "tiempoRetorno": 1,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "INCIDENCIA",
            "subMotivo": "CAIDA DE SISTEMA",
            "subNivel": "AGENDADOR",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "ERROR DE DIRECCION",
            "subMotivo": "DIRECCION ERRADA",
            "subNivel": "SE DERIVA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "CLIENTE NO DESEA",
            "subMotivo": "DEMORA EN INST",
            "subNivel": "SE CANCELA ",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "CLIENTE NO DESEA",
            "subMotivo": "MALA INF CC",
            "subNivel": "SE CANCELA ",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "CLIENTE NO DESEA",
            "subMotivo": "VIAJE O MUDANZA",
            "subNivel": "SE CANCELA ",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "CLIENTE NO DESEA",
            "subMotivo": "NO BRINDA DETALLE",
            "subNivel": "SE CANCELA ",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "CLIENTE NO IDENTIFICADO",
            "subMotivo": "ES PRIMERA DEVOLUCION",
            "subNivel": "SE SUSPENDE",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "CLIENTE NO IDENTIFICADO",
            "subMotivo": "NO ES PRIMERA DEVOLUCION",
            "subNivel": "SE CANCELA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "CLIENTE NO IDENTIFICADO",
            "subMotivo": "CLIENTE NO IDENTIFICADO",
            "subNivel": "SE CANCELA ",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "CLIENTE NO DESEA",
            "subMotivo": "SERVICIO RESTABLECIDO",
            "subNivel": "SE CANCELA",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "RECHAZADO",
            "subMotivo": "CTO NO DESPLEGADO",
            "subNivel": "NO APLICA SOLICITUD",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        },
        {
            "quiebre": "bo linea de rescate mxa",
            "motivo": "RECHAZADO",
            "subMotivo": "BORNES NO DISPONIBLE",
            "subNivel": "NO APLICA SOLICITUD",
            "estado": "CERRADO",
            "tiempoRetorno": 0,
            "quiebrederivacion": "",
            "tipoatencion": "",
            "enable": true
        }
    ]